# Generated by Django 4.1.5 on 2023-03-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("date", models.IntegerField(primary_key=True, serialize=False)),
                ("hours", models.IntegerField(default=0)),
            ],
        ),
    ]
