# Generated by Django 4.1.5 on 2023-03-15 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0002_delete_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("name", models.CharField(max_length=50)),
                (
                    "emp_id",
                    models.IntegerField(
                        max_length=10, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "hours",
                    models.IntegerField(
                        choices=[(9, "Fullday"), (4.5, "HalfDay"), (0, "Leave")],
                        default=0,
                        max_length=3,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.employee",
                    ),
                ),
            ],
        ),
    ]
