# Generated by Django 4.1.5 on 2023-03-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="hours",
            field=models.IntegerField(
                choices=[(9, "Fullday"), (4, "HalfDay"), (0, "Leave")],
                default=0,
                max_length=3,
            ),
        ),
    ]
